local bootstrap = require('nvimconf2.bootstrap')

require('nvimconf2.options')
require('nvimconf2.oil').setup()
require('nvimconf2.keymaps')
require('nvimconf2.fff').setup(bootstrap.fff_available)
require('nvimconf2.grug_far').setup()
require('nvimconf2.lsp').setup()
require('nvimconf2.blink').setup()
require('nvimconf2.treesitter_select').setup()
