local M = {}

local p = {
	bg = "#16181a",
	bg_alt = "#1e2124",
	bg_highlight = "#3c4048",
	fg = "#ffffff",
	grey = "#7b8496",
	blue = "#5ea1ff",
	green = "#5eff6c",
	cyan = "#5ef1ff",
	red = "#ff6e5e",
	yellow = "#f1ff5e",
	magenta = "#ff5ef1",
	pink = "#ff5ea0",
	orange = "#ffbd5e",
	purple = "#bd5eff",
	black = "#000000",
}

p.bg_solid = p.bg
p.bg = "NONE"

local function hex_to_rgb(hex)
	if hex == "NONE" then
		return nil
	end

	return {
		tonumber(hex:sub(2, 3), 16),
		tonumber(hex:sub(4, 5), 16),
		tonumber(hex:sub(6, 7), 16),
	}
end

local function blend(color1, color2, weight)
	local rgb1 = hex_to_rgb(color1)
	local rgb2 = hex_to_rgb(color2)
	local mixed = {}

	for i = 1, 3 do
		mixed[i] = math.floor(rgb1[i] * weight + rgb2[i] * (1 - weight))
	end

	return string.format("#%02x%02x%02x", mixed[1], mixed[2], mixed[3])
end

local function set_highlights(groups)
	for group, spec in pairs(groups) do
		vim.api.nvim_set_hl(0, group, spec)
	end
end

function M.apply()
	if vim.g.colors_name then
		vim.cmd("hi clear")
	end

	vim.o.termguicolors = true
	vim.g.colors_name = "nvimconf2"
	vim.opt.fillchars:append({ eob = " " })

	local blink_border = blend(p.bg_highlight, p.grey, 0.7)

	set_highlights({
		Normal = { fg = p.fg, bg = p.bg },
		NormalNC = { fg = p.fg, bg = p.bg },
		NormalFloat = { fg = p.fg, bg = p.bg },
		FloatBorder = { fg = p.bg_highlight, bg = p.bg },
		FloatTitle = { fg = p.cyan, bg = p.bg, bold = true },
		Cursor = { fg = p.bg_solid, bg = p.fg },
		CursorLine = { bg = "#33334c" },
		CursorColumn = { bg = p.bg_highlight },
		CursorLineNr = { fg = p.grey, bold = true },
		LineNr = { fg = blend(p.bg_highlight, p.fg, 0.9) },
		SignColumn = { fg = p.grey, bg = p.bg },
		FoldColumn = { fg = p.grey, bg = p.bg },
		Folded = { fg = p.grey, bg = p.bg },
		EndOfBuffer = { fg = p.bg },
		NonText = { fg = blend(p.bg_solid, p.grey, 0.55) },
		Whitespace = { fg = p.bg_highlight },
		VertSplit = { fg = p.bg_highlight, bg = p.bg },
		WinSeparator = { fg = p.bg_highlight, bg = p.bg },
		ColorColumn = { bg = p.bg_highlight },
		MatchParen = { fg = p.pink, bg = p.bg_highlight, bold = true },
		Visual = { fg = p.black, bg = p.orange },
		VisualNOS = { bg = p.bg_highlight },
		Search = { fg = p.bg_alt, bg = p.fg },
		CurSearch = { fg = p.bg_alt, bg = p.cyan },
		IncSearch = { fg = p.bg_alt, bg = p.cyan },
		Pmenu = { fg = p.fg, bg = p.bg },
		PmenuSel = { fg = p.fg, bg = p.bg_highlight },
		PmenuSbar = { bg = p.bg_highlight },
		PmenuThumb = { bg = p.grey },
		StatusLine = { fg = p.fg, bg = p.bg },
		StatusLineNC = { fg = p.grey, bg = p.bg },
		TabLine = { fg = p.grey, bg = p.bg },
		TabLineFill = { fg = p.grey, bg = p.bg },
		TabLineSel = { fg = p.fg, bg = p.bg_highlight, bold = true },
		WinBar = { fg = p.fg, bg = p.bg },
		WinBarNC = { fg = p.grey, bg = p.bg },
		Directory = { fg = p.blue },
		Question = { fg = p.yellow },
		ErrorMsg = { fg = p.red },
		WarningMsg = { fg = p.orange },
		MoreMsg = { fg = p.blue },
		Title = { fg = p.fg, bold = true },
		QuickFixLine = { bg = p.bg_highlight },
		qfLineNr = { fg = p.grey },
		qfFileName = { fg = p.blue },
		DiffAdd = { bg = blend(p.bg_solid, p.green, 0.8) },
		DiffChange = { bg = blend(p.bg_solid, p.blue, 0.8) },
		DiffDelete = { bg = blend(p.bg_solid, p.red, 0.8) },
		DiffText = { bg = blend(p.bg_solid, p.orange, 0.8) },
		Added = { fg = p.green },
		Removed = { fg = p.red },
		Comment = { fg = p.grey },
		Constant = { fg = p.pink },
		String = { fg = p.green },
		Character = { fg = p.green },
		Number = { fg = p.orange },
		Boolean = { fg = p.cyan },
		Float = { fg = p.orange },
		Identifier = { fg = p.fg },
		Function = { fg = p.blue },
		Statement = { fg = p.magenta },
		Conditional = { link = "Statement" },
		Repeat = { link = "Statement" },
		Label = { fg = p.orange },
		Operator = { fg = p.purple },
		Keyword = { fg = p.orange },
		Exception = { link = "Statement" },
		PreProc = { fg = p.cyan },
		Include = { link = "PreProc" },
		Define = { link = "PreProc" },
		Macro = { link = "PreProc" },
		PreCondit = { link = "PreProc" },
		Type = { fg = p.purple },
		StorageClass = { link = "Type" },
		Structure = { link = "Type" },
		Typedef = { link = "Type" },
		Special = { fg = p.pink },
		SpecialChar = { link = "Special" },
		Delimiter = { fg = p.fg },
		SpecialComment = { fg = p.grey },
		Underlined = { underline = true },
		Bold = { bold = true },
		Italic = { italic = true },
		Error = { fg = p.red },
		Todo = { fg = p.purple, bold = true },
		markdownH1 = { fg = p.orange, bold = true },
		markdownH2 = { fg = p.cyan, bold = true },
		markdownH3 = { fg = p.blue, bold = true },
		markdownH4 = { fg = p.purple, bold = true },
		markdownH5 = { fg = p.magenta, bold = true },
		markdownH6 = { fg = p.green, bold = true },
		markdownCode = { fg = p.cyan },
		markdownCodeBlock = { fg = p.cyan },
		markdownLinkText = { fg = p.blue, underline = true },
		LspReferenceText = { bg = p.bg_highlight },
		LspReferenceRead = { bg = p.bg_highlight },
		LspReferenceWrite = { bg = p.bg_highlight },
		LspCodeLens = { fg = p.grey },
		LspInlayHint = { fg = p.grey },
		LspSignatureActiveParameter = { fg = p.orange, bold = true },
		DiagnosticError = { fg = p.red },
		DiagnosticWarn = { fg = p.yellow },
		DiagnosticInfo = { fg = p.blue },
		DiagnosticHint = { fg = p.cyan },
		DiagnosticUnnecessary = { fg = p.grey },
		DiagnosticSignError = { link = "DiagnosticError" },
		DiagnosticSignWarn = { link = "DiagnosticWarn" },
		DiagnosticSignInfo = { link = "DiagnosticInfo" },
		DiagnosticSignHint = { link = "DiagnosticHint" },
		DiagnosticFloatingError = { link = "DiagnosticError" },
		DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
		DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
		DiagnosticFloatingHint = { link = "DiagnosticHint" },
		DiagnosticVirtualTextError = { fg = p.red },
		DiagnosticVirtualTextWarn = { fg = p.yellow },
		DiagnosticVirtualTextInfo = { fg = p.blue },
		DiagnosticVirtualTextHint = { fg = p.cyan },
		DiagnosticUnderlineError = { undercurl = true, sp = p.red },
		DiagnosticUnderlineWarn = { undercurl = true, sp = p.yellow },
		DiagnosticUnderlineInfo = { undercurl = true, sp = p.blue },
		DiagnosticUnderlineHint = { undercurl = true, sp = p.cyan },
		BlinkCmpMenu = { link = "Pmenu" },
		BlinkCmpMenuBorder = { fg = blink_border },
		BlinkCmpMenuSelection = { bg = p.bg_highlight },
		BlinkCmpLabel = { fg = p.fg },
		BlinkCmpLabelDeprecated = { fg = p.grey, strikethrough = true },
		BlinkCmpLabelMatch = { fg = p.cyan },
		BlinkCmpDoc = { link = "NormalFloat" },
		BlinkCmpDocBorder = { link = "BlinkCmpMenuBorder" },
		BlinkCmpDocCursorLine = { link = "Visual" },
		BlinkCmpSignatureHelp = { link = "NormalFloat" },
		BlinkCmpSignatureHelpBorder = { link = "BlinkCmpMenuBorder" },
		BlinkCmpSignatureHelpActiveParameter = { fg = p.cyan },
		BlinkCmpKindText = { fg = p.green },
		BlinkCmpKindMethod = { fg = p.blue },
		BlinkCmpKindFunction = { fg = p.blue },
		BlinkCmpKindConstructor = { fg = p.purple },
		BlinkCmpKindField = { fg = p.green },
		BlinkCmpKindVariable = { fg = p.orange },
		BlinkCmpKindProperty = { fg = p.red },
		BlinkCmpKindClass = { fg = p.blue },
		BlinkCmpKindInterface = { fg = p.blue },
		BlinkCmpKindStruct = { fg = p.blue },
		BlinkCmpKindModule = { fg = p.blue },
		BlinkCmpKindUnit = { fg = p.orange },
		BlinkCmpKindValue = { fg = p.orange },
		BlinkCmpKindEnum = { fg = p.orange },
		BlinkCmpKindEnumMember = { fg = p.orange },
		BlinkCmpKindKeyword = { fg = p.magenta },
		BlinkCmpKindConstant = { fg = p.pink },
		BlinkCmpKindSnippet = { fg = p.green },
		BlinkCmpKindColor = { fg = p.green },
		BlinkCmpKindFile = { fg = p.green },
		BlinkCmpKindReference = { fg = p.green },
		BlinkCmpKindFolder = { fg = p.green },
		BlinkCmpKindEvent = { fg = p.green },
		BlinkCmpKindOperator = { fg = p.magenta },
		BlinkCmpKindTypeParameter = { fg = p.pink },
		GrugFarHelpHeader = { link = "Comment" },
		GrugFarHelpHeaderKey = { fg = p.cyan, bold = true },
		GrugFarHelpWinHeader = { fg = p.blue, bold = true },
		GrugFarHelpWinActionPrefix = { fg = p.purple },
		GrugFarHelpWinActionText = { link = "Normal" },
		GrugFarHelpWinActionKey = { fg = p.cyan, bold = true },
		GrugFarHelpWinActionDescription = { link = "Comment" },
		GrugFarInputLabel = { fg = p.orange, bold = true },
		GrugFarInputPlaceholder = { fg = blend(p.bg_highlight, p.fg, 0.9), italic = true },
		GrugFarResultsHeader = { link = "Comment" },
		GrugFarResultsStats = { fg = p.yellow },
		GrugFarResultsActionMessage = { fg = p.bg_solid, bg = p.green, bold = true },
		GrugFarResultsMatch = { fg = p.cyan, bg = blend(p.bg_solid, p.cyan, 0.85), bold = true },
		GrugFarResultsChangeIndicator = { fg = p.cyan },
		GrugFarResultsPath = { fg = p.blue, bold = true, underline = true },
		GrugFarResultsRgCmdHeader = { link = "GrugFarResultsPath" },
		GrugFarResultsLineNo = { fg = p.pink, bold = true },
		GrugFarResultsLineColumn = { link = "GrugFarResultsLineNo" },
		["@annotation"] = { link = "PreProc" },
		["@attribute"] = { link = "PreProc" },
		["@boolean"] = { link = "Boolean" },
		["@character"] = { link = "Character" },
		["@character.special"] = { link = "SpecialChar" },
		["@comment"] = { link = "Comment" },
		["@conditional"] = { link = "Conditional" },
		["@constant"] = { link = "Constant" },
		["@constant.builtin"] = { link = "Special" },
		["@constant.macro"] = { link = "Define" },
		["@constructor"] = { link = "Special" },
		["@exception"] = { link = "Exception" },
		["@field"] = { link = "Identifier" },
		["@float"] = { link = "Float" },
		["@function"] = { link = "Function" },
		["@function.builtin"] = { link = "Function" },
		["@function.call"] = { link = "@function" },
		["@function.macro"] = { link = "Macro" },
		["@include"] = { link = "Include" },
		["@keyword"] = { link = "Keyword" },
		["@keyword.function"] = { link = "Keyword" },
		["@keyword.operator"] = { link = "@operator" },
		["@keyword.return"] = { link = "@keyword" },
		["@keyword.type"] = { fg = p.orange, italic = true },
		["@label"] = { link = "Label" },
		["@markup.heading.1"] = { link = "markdownH1" },
		["@markup.heading.2"] = { link = "markdownH2" },
		["@markup.heading.3"] = { link = "markdownH3" },
		["@markup.heading.4"] = { link = "markdownH4" },
		["@markup.heading.5"] = { link = "markdownH5" },
		["@markup.heading.6"] = { link = "markdownH6" },
		["@markup.italic"] = { fg = p.blue, italic = true },
		["@markup.link.label"] = { link = "Label" },
		["@markup.link.label.markdown_inline"] = { fg = p.cyan },
		["@markup.link.markdown_inline"] = { fg = p.blue },
		["@markup.link.url"] = { fg = p.blue, underline = true },
		["@markup.list.checked"] = { fg = p.green, bold = true },
		["@markup.list.unchecked"] = { fg = p.magenta, bold = true },
		["@markup.quote"] = { link = "Comment" },
		["@markup.strong"] = { fg = p.pink, bold = true },
		["@method"] = { link = "Function" },
		["@method.call"] = { link = "@method" },
		["@module"] = { fg = p.magenta },
		["@namespace"] = { link = "Include" },
		["@number"] = { link = "Number" },
		["@operator"] = { link = "Operator" },
		["@parameter"] = { link = "Identifier" },
		["@preproc"] = { link = "PreProc" },
		["@property"] = { link = "Identifier" },
		["@punctuation.bracket"] = { link = "Delimiter" },
		["@punctuation.delimiter"] = { link = "Delimiter" },
		["@punctuation.special"] = { link = "Delimiter" },
		["@repeat"] = { link = "Repeat" },
		["@storageclass"] = { link = "StorageClass" },
		["@string"] = { link = "String" },
		["@string.escape"] = { link = "SpecialChar" },
		["@string.regex"] = { link = "String" },
		["@string.special"] = { link = "SpecialChar" },
		["@symbol"] = { link = "Identifier" },
		["@tag"] = { link = "Label" },
		["@tag.attribute"] = { link = "@property" },
		["@tag.delimiter"] = { link = "Delimiter" },
		["@text.literal"] = { link = "String" },
		["@text.math"] = { link = "Special" },
		["@text.note"] = { link = "SpecialComment" },
		["@text.reference"] = { link = "Constant" },
		["@text.strike"] = { strikethrough = true },
		["@text.todo"] = { link = "Todo" },
		["@text.underline"] = { underline = true },
		["@text.uri"] = { link = "Underlined" },
		["@text.warning"] = { link = "Todo" },
		["@type"] = { link = "Type" },
		["@type.builtin"] = { fg = blend(p.purple, p.pink, 0.65) },
		["@type.definition"] = { link = "Typedef" },
		["@type.qualifier"] = { link = "@keyword" },
		["@variable"] = { fg = p.fg },
		["@variable.builtin"] = { link = "Special" },
	})
end

return M
